variables:
  UV_VERSION: 0.9
  PYTHON_VERSION: 3.14
  BASE_LAYER: bookworm
  UV_CACHE_DIR: .uv-cache
  UV_SYSTEM_PYTHON: 1

stages:
  - pre-commit
  - test

pre-commit-check:
  stage: pre-commit
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR
  script:
    - uv sync --all-extras
    - uv run pre-commit run --all-files

pytest:
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR
  script:
    - uv sync --all-extras
    - uv run pytest
  artifacts:
    reports:
      junit: reports/test.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage.xml
